version: 1.0.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- cmd: nuget restore ./SociumApp/SociumApp.sln
build:
  project: ./SociumApp/SociumApp.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
services:
  - mssql2016

environment:
  COVERALLS_REPO_TOKEN:
    secure: V3nyoA0koaeHhNBYaeZ4K2RdMT25zg51y95XuzvmmHtFva5mtX3q2xZmU9zNgrpI

after_test: 
        - SociumApp\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"SociumApp\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single SociumApp\SociumApp.Tests\bin\Debug\SociumApp.Tests.dll" -output:cover.xml

        - SociumApp\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml